apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bugsink
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prem-prakash/homeserver.git
    targetRevision: main
    path: gitops/bugsink
  destination:
    server: https://kubernetes.default.svc
    namespace: bugsink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
