apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: werify-production
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: werify-production
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GHCR_USERNAME }}",
                "password": "{{ .GHCR_TOKEN }}",
                "auth": "{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}"
              }
            }
          }
  data:
    - secretKey: GHCR_USERNAME
      remoteRef:
        key: GHCR_USERNAME
    - secretKey: GHCR_TOKEN
      remoteRef:
        key: GHCR_TOKEN
