# This secret stores the Infisical Machine Identity credentials
#
# Option 1 - Create via kubectl (recommended, don't commit secrets):
#   kubectl create secret generic infisical-credentials \
#     --namespace external-secrets \
#     --from-literal=clientId="$INFISICAL_CLIENT_ID" \
#     --from-literal=clientSecret="$INFISICAL_CLIENT_SECRET"
#
# Option 2 - Apply with envsubst:
#   export INFISICAL_CLIENT_ID="your-client-id"
#   export INFISICAL_CLIENT_SECRET="your-client-secret"
#   envsubst < infisical-credentials.yaml | kubectl apply -f -
#
apiVersion: v1
kind: Secret
metadata:
  name: infisical-credentials
  namespace: external-secrets
type: Opaque
stringData:
  clientId: "${INFISICAL_CLIENT_ID}"
  clientSecret: "${INFISICAL_CLIENT_SECRET}"
