apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bugsink-secrets
  namespace: bugsink
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bugsink
    kind: ClusterSecretStore
  target:
    name: bugsink-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
