apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bugsink-data
  namespace: bugsink
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-static
  volumeName: bugsink-data
  resources:
    requests:
      storage: 10Gi
