apiVersion: v1
kind: PersistentVolume
metadata:
  name: werify-staging-uploads
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-static
  local:
    path: /mnt/k8s-persistent/pvs/werify-staging-uploads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-apps  # Update with actual node name from: kubectl get nodes
